version: '3.1'

volumes:
  pg_project:

services:
  MUSICGEEK_db:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MUSICGEEKdb
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432